# Q19. Explain the Difference Between `analogRead()` and `analogWrite()`. What is PWM and Why is it Used? Give a Practical IoT Example for Each.

## Introduction

Microcontrollers such as Arduino interact with the physical world through sensors and actuators. Sensors produce analog signals such as temperature, light intensity, and humidity, while actuators such as LEDs and motors often require varying levels of power rather than simply ON or OFF states.

To handle these requirements, Arduino provides two important functions:

* `analogRead()`
* `analogWrite()`

Although their names appear similar, they perform completely different operations.

---

# 1. analogRead()

## Definition

`analogRead()` is used to read an analog voltage from one of the analog input pins of the Arduino.

The Arduino UNO contains a **10-bit Analog-to-Digital Converter (ADC)** which converts an analog voltage into a digital number.

The input voltage range is:

```text id="d0v4vl"
0V to 5V
```

The corresponding digital values range from:

```text id="epoc7q"
0 to 1023
```

This means:

| Input Voltage | ADC Output |
| ------------- | ---------- |
| 0V            | 0          |
| 2.5V          | 512        |
| 5V            | 1023       |

---

## Syntax

```cpp id="n0hck9"
int sensorValue = analogRead(A0);
```

---

## Example

```cpp id="nnskri"
int ldrValue;

void setup() {
    Serial.begin(9600);
}

void loop() {
    ldrValue = analogRead(A0);
    Serial.println(ldrValue);
}
```

Here the Arduino reads the voltage generated by an LDR sensor and prints the corresponding digital value.

---

## Applications of analogRead()

* Reading temperature sensors
* Measuring light intensity
* Monitoring soil moisture
* Reading gas sensor outputs
* Potentiometer position measurement

---

## IoT Example

### Smart Irrigation System

A soil moisture sensor connected to an analog pin continuously measures moisture levels.

If the value falls below a threshold, the system automatically activates a water pump.

Thus:

```text id="9nsrt9"
Sensor → analogRead() → Decision → Pump Control
```

---

# 2. analogWrite()

## Definition

Unlike `analogRead()`, `analogWrite()` does not generate a true analog voltage.

Instead, it generates a **Pulse Width Modulated (PWM)** signal that simulates analog output.

The output values range from:

```text id="0u7b14"
0 to 255
```

because Arduino UNO uses an **8-bit PWM resolution**.

---

## Syntax

```cpp id="6jlwmj"
analogWrite(pin, value);
```

Example:

```cpp id="h2jlwm"
analogWrite(9, 128);
```

---

## PWM Values

| Value | Duty Cycle | Effective Output  |
| ----- | ---------- | ----------------- |
| 0     | 0%         | OFF               |
| 64    | 25%        | Low brightness    |
| 128   | 50%        | Medium brightness |
| 192   | 75%        | High brightness   |
| 255   | 100%       | Fully ON          |

---

## Example

```cpp id="4jlwmj"
analogWrite(9, 200);
```

This generates a PWM signal with approximately 78% duty cycle.

---

## Applications of analogWrite()

* LED brightness control
* Motor speed control
* Fan speed regulation
* Heater power control
* Audio tone generation

---

## IoT Example

### Smart Street Lighting

A smart street light uses an LDR to measure ambient light.

During the evening, the controller uses:

```cpp id="6jljwj"
analogWrite(ledPin, brightness);
```

to gradually increase street light brightness.

This saves energy and extends lamp lifetime.

---

# What is PWM?

PWM stands for **Pulse Width Modulation**.

PWM is a technique used to simulate analog voltage using a digital signal.

Instead of changing voltage continuously, the microcontroller rapidly switches the output ON and OFF.

By changing the percentage of time the signal stays ON, different average voltages can be produced.

---

## Duty Cycle

The percentage of time the signal remains HIGH during one complete cycle is called the **duty cycle**.

Mathematically:

```text id="g1a0yo"
Duty Cycle = (ON Time / Total Time) × 100
```

---

## Example

### 25% Duty Cycle

```text id="n3t4yz"
HIGH ___
LOW  ___________
```

Average output voltage:

```text id="d52od2"
1.25V
```

---

### 50% Duty Cycle

```text id="vcgvya"
HIGH _____
LOW  _____
```

Average output voltage:

```text id="ih76mv"
2.5V
```

---

### 100% Duty Cycle

```text id="c1crf4"
HIGH ____________
```

Average output voltage:

```text id="lkx62n"
5V
```

---

# Why is PWM Used?

Generating true analog voltages requires Digital-to-Analog Converters (DACs), which increase system complexity and cost.

PWM provides a simple and efficient alternative using ordinary digital pins.

Advantages include:

* Low cost implementation
* High efficiency
* Low power loss
* Simple hardware requirements
* Fine control over output power

---

# Arduino PWM Pins

On Arduino UNO, PWM is available on:

```text id="w5tb75"
3, 5, 6, 9, 10 and 11
```

These pins are marked with the symbol:

```text id="ehzkt1"
~
```

---

# Comparison Between analogRead() and analogWrite()

| Parameter      | analogRead()        | analogWrite()       |
| -------------- | ------------------- | ------------------- |
| Purpose        | Read analog voltage | Generate PWM output |
| Pin Type       | Analog input pins   | PWM output pins     |
| Data Flow      | Input               | Output              |
| Resolution     | 10-bit              | 8-bit               |
| Range          | 0–1023              | 0–255               |
| Hardware Used  | ADC                 | PWM Timer           |
| Example Device | LDR Sensor          | LED or Motor        |

---

# Real-World IoT Example

Consider a smart greenhouse:

### Input Stage

An LDR sensor measures sunlight intensity using:

```cpp id="l3ye5v"
analogRead(A0);
```

### Output Stage

The controller adjusts LED grow light brightness using:

```cpp id="yhlq0g"
analogWrite(9, brightness);
```

Thus the system automatically maintains optimum lighting conditions for plant growth.

---

# Conclusion

`analogRead()` converts analog sensor signals into digital values using the Arduino's ADC, whereas `analogWrite()` generates PWM signals to simulate analog output.

PWM allows microcontrollers to efficiently control devices such as LEDs, motors, and fans without requiring dedicated analog output hardware.

Together, these functions form the foundation of many IoT and embedded systems applications.
