# Q30. Explain I2C Protocol with Respect to IoT Sensor Communication. What are SDA and SCL Lines? How Does I2C Addressing Work? Name Three Common IoT Sensors that Use I2C.

## Introduction

Modern IoT systems often require multiple sensors, displays, and communication modules to be connected to a single microcontroller. If every device used separate communication wires, the wiring complexity would increase significantly and many microcontroller pins would be consumed.

To solve this problem, serial communication protocols such as I2C were developed.

I2C is one of the most widely used communication protocols in embedded systems because it allows multiple devices to communicate using only two wires.

---

# What is I2C?

I2C stands for **Inter-Integrated Circuit**.

It is a synchronous serial communication protocol developed by Philips Semiconductor (now NXP) for communication between integrated circuits on the same circuit board.

I2C allows multiple devices to communicate using only two communication lines regardless of the number of connected devices.

---

# Why is I2C Used in IoT Systems?

IoT systems often include multiple devices such as:

* Temperature sensors
* Pressure sensors
* OLED displays
* Accelerometers
* Real Time Clock modules

Using separate communication lines for each device would require many pins and complicated wiring.

I2C simplifies this by allowing all devices to share the same communication bus.

---

# The Two I2C Lines

I2C communication uses only two wires:

## 1. SDA (Serial Data Line)

The SDA line carries the actual data being transmitted between devices.

Both the master and slave devices use this line to send and receive information.

Examples of data transmitted through SDA include:

* Temperature readings
* Humidity values
* Commands
* Sensor configurations

---

## 2. SCL (Serial Clock Line)

The SCL line carries the clock signal generated by the master device.

This clock signal synchronizes communication between all devices connected to the bus.

Every bit transmitted on SDA is synchronized using SCL.

---

## Arduino UNO Pins

| Signal | Arduino UNO Pin |
| ------ | --------------- |
| SDA    | A4              |
| SCL    | A5              |

---

## ESP32 Default Pins

| Signal | ESP32 Pin |
| ------ | --------- |
| SDA    | GPIO21    |
| SCL    | GPIO22    |

These pins can be changed in software if required.

---

# Master and Slave Devices

I2C communication follows a **master-slave architecture**.

## Master Device

The master device:

* Initiates communication
* Generates clock signals
* Selects slave devices
* Requests or sends data

Examples:

* Arduino UNO
* ESP32
* Raspberry Pi

---

## Slave Device

The slave device:

* Waits for requests from the master
* Responds when addressed
* Sends or receives data

Examples:

* Sensors
* OLED displays
* RTC modules

---

# How Does I2C Communication Work?

Suppose an ESP32 wants to read temperature from a sensor.

The communication sequence is:

### Step 1

The master generates a START condition.

### Step 2

The master sends the address of the target sensor.

### Step 3

The addressed sensor responds with an acknowledgement (ACK).

### Step 4

The master requests data.

### Step 5

The sensor sends the requested data.

### Step 6

The master generates a STOP condition.

---

## Communication Flow

```text id="g2pxm2"
ESP32 (Master)
      |
      | Address + Read Request
      |
BMP280 Sensor (Slave)
      |
      | Temperature Data
      |
ESP32 receives data
```

---

# I2C Addressing

One of the biggest advantages of I2C is that multiple devices can share the same communication bus.

This is possible because every I2C device has a unique address.

The master communicates with a specific slave by sending its address first.

Only the matching device responds while all other devices ignore the transmission.

---

## Example Addresses

| Device       | Address |
| ------------ | ------- |
| OLED Display | 0x3C    |
| MPU6050      | 0x68    |
| BME280       | 0x76    |
| DS3231 RTC   | 0x68    |

---

## Example

Suppose an ESP32 communicates with three devices:

```text id="uvzv3r"
OLED Display  -> 0x3C
MPU6050       -> 0x68
BME280        -> 0x76
```

If the ESP32 sends:

```text id="lmyjtp"
Address = 0x76
```

Only the BME280 sensor responds.

---

# 7-bit and 10-bit Addressing

I2C primarily uses **7-bit addresses**.

With 7 bits:

```text id="zw7n5f"
2^7 = 128 possible addresses
```

Some advanced devices support 10-bit addressing, but 7-bit addressing is sufficient for most IoT applications.

---

# Pull-up Resistors in I2C

The SDA and SCL lines use **open-drain outputs**, meaning devices can pull the lines LOW but cannot drive them HIGH.

Therefore, pull-up resistors are required to bring the lines back to HIGH state.

Typical values are:

```text id="r3m8zp"
4.7 kΩ or 10 kΩ
```

Many sensor modules already include these resistors on the PCB.

---

# Advantages of I2C

## 1. Only Two Wires Required

Reduces wiring complexity.

## 2. Supports Multiple Devices

Many devices can share the same bus.

## 3. Saves Microcontroller Pins

Ideal for compact IoT systems.

## 4. Easy Expansion

Additional sensors can be added without major rewiring.

## 5. Widely Supported

Most modern sensors support I2C communication.

---

# Disadvantages of I2C

* Lower speed compared to SPI.
* Limited communication distance.
* Address conflicts may occur if two devices have the same address.
* Performance decreases with very large numbers of devices.

---

# Common IoT Sensors Using I2C

## 1. MPU6050

A six-axis accelerometer and gyroscope used in drones, robots, and motion tracking systems.

---

## 2. BMP280/BME280

Environmental sensors used for measuring:

* Temperature
* Pressure
* Humidity

Commonly used in weather stations.

---

## 3. DS3231 Real Time Clock Module

Provides highly accurate timekeeping even during power failures.

Used in data loggers and automation systems.

---

# Real-World IoT Example

Consider a smart weather station built using an ESP32:

* BME280 measures temperature and humidity.
* DS3231 provides timestamps.
* OLED display shows readings.

All three devices share the same SDA and SCL lines:

```text id="6ukpnh"
ESP32
 ├── BME280 (0x76)
 ├── OLED Display (0x3C)
 └── DS3231 RTC (0x68)
```

Thus only two communication wires are required regardless of the number of devices.

---

# Conclusion

I2C is a simple and efficient communication protocol widely used in IoT and embedded systems. It enables multiple devices to communicate using only two wires: SDA for data transfer and SCL for clock synchronization.

Through unique addressing, many sensors can share the same communication bus, reducing wiring complexity and conserving microcontroller pins. This makes I2C one of the most important communication protocols in modern IoT applications.
